pipeline {
    agent any
    stages {
        stage('编译代码') {
            steps {
                //
                sh 'mvn package'
                sh 'cp target/*.jar docker/ && chmod 777 docker/update.sh'
            }
        }
        stage('构建docker镜像') {
            steps {
                sh 'docker/update.sh'
            }
        }
        stage('清理代码') {
                steps {
                    //
                    sh 'rm -rf * &&  rm -rf .git*'
                }
            }
        }
}
