pipeline {
    agent any
    stages {
        stage('构建jar包') {
            steps {
                //
                sh 'mvn package'
                sh 'cp target/*.jar docker/ && chmod 777 docker/update.sh'

            }
        }
        stage('构建docker镜像') {
            steps {
                sh 'docker/update.sh'
            }
        }
        stage('清理文件') {
                steps {
                    //
                    sh 'rm -rf *'
                }
            }
        }
}
